default: &default
  adapter: postgresql
  encoding: unicode
  username: mac
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wecasatest_development

test:
  <<: *default
  database: wecasatest_test

production:
  <<: *default
  database: wecasatest_production
  username: mac
  password: <%= ENV['WECASATEST_DATABASE_PASSWORD'] %>
