default: &default
  adapter: postgresql
  encoding: unicode
  # username: <%= ENV['DATABASE_USERNAME'] || 'default_username' %>
  # password: <%= ENV['DATABASE_PASSWORD'] || 'default_password' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wecasatest_development

test:
  <<: *default
  database: wecasatest_test

production:
  <<: *default
  database: wecasatest_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
